#!/usr/bin/env python3
"""Generate a compact GitHub profile statistics SVG from public repository data."""
from __future__ import annotations

import html
import json
import os
import urllib.parse
import urllib.request
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

OWNER = "Mohannad-Mahdi-Dev"
API = "https://api.github.com"
OUTPUT = Path(__file__).resolve().parents[1] / "github-stats.svg"
TOKEN = os.environ.get("GITHUB_TOKEN", "").strip()


def get_json(path: str):
    url = path if path.startswith("http") else API + path
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "Mohannad-Mahdi-Dev-profile-stats",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def text(x: float, y: float, value: object, size: int, fill: str = "#E6EDF3", weight: str = "400", anchor: str = "start") -> str:
    return f'<text x="{x}" y="{y}" fill="{fill}" font-family="Arial,DejaVu Sans,sans-serif" font-size="{size}px" font-weight="{weight}" text-anchor="{anchor}">{esc(value)}</text>'


def main() -> None:
    user = get_json(f"/users/{OWNER}")
    repos = get_json(f"/users/{OWNER}/repos?per_page=100&type=owner&sort=updated")

    stars = sum(int(repo.get("stargazers_count", 0)) for repo in repos)
    forks = sum(int(repo.get("forks_count", 0)) for repo in repos)
    languages: Counter[str] = Counter()
    for repo in repos:
        if repo.get("fork"):
            continue
        language_url = repo.get("languages_url")
        if not language_url:
            continue
        try:
            languages.update({k: int(v) for k, v in get_json(language_url).items()})
        except Exception:
            # One unavailable language endpoint should not prevent a daily refresh.
            continue
    top_language = languages.most_common(1)[0][0] if languages else "Not available"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    cards = [
        ("PUBLIC REPOSITORIES", user.get("public_repos", len(repos)), "#58A6FF"),
        ("TOTAL STARS", stars, "#F2CC60"),
        ("TOTAL FORKS", forks, "#BC8CFF"),
        ("FOLLOWERS", user.get("followers", 0), "#3FB950"),
        ("TOP LANGUAGE", top_language, "#F778BA"),
    ]

    pieces = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="286" viewBox="0 0 1000 286" role="img" aria-labelledby="title desc">',
        '<title id="title">GitHub public activity snapshot for Mohannad Mahdi</title>',
        '<desc id="desc">Automatically generated from public GitHub repository data.</desc>',
        '<rect width="1000" height="286" rx="18" fill="#0D1117"/>',
        '<rect x="1" y="1" width="998" height="284" rx="17" fill="none" stroke="#30363D"/>',
        text(34, 42, "github.com / Mohannad-Mahdi-Dev", 18, "#8B949E", "400"),
        text(34, 76, "Public GitHub snapshot", 30, "#F0F6FC", "700"),
        text(966, 43, f"refreshed {generated}", 14, "#8B949E", "400", "end"),
    ]

    x_positions = [34, 222, 410, 598, 786]
    for x, (label, value, color) in zip(x_positions, cards):
        pieces.extend([
            f'<rect x="{x}" y="104" width="160" height="112" rx="12" fill="#161B22" stroke="#30363D"/>',
            f'<rect x="{x}" y="104" width="160" height="4" rx="2" fill="{color}"/>',
            text(x + 16, 135, label, 11, "#8B949E", "700"),
            text(x + 16, 174, value, 25 if len(str(value)) < 14 else 18, "#F0F6FC", "700"),
            text(x + 16, 198, "public data", 12, "#8B949E", "400"),
        ])

    pieces.extend([
        text(34, 254, "Automatically generated by GitHub Actions • This is an activity snapshot, not a measure of skill.", 13, "#8B949E", "400"),
        "</svg>",
    ])
    OUTPUT.write_text("\n".join(pieces) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
